#!/bin/sh

LUAROCKS_SYSCONFDIR='/usr/local/etc/luarocks' exec '/usr/local/bin/lua' -e 'package.path="/workspaces/lua-docker/./lua_modules/share/lua/5.4/?.lua;/workspaces/lua-docker/./lua_modules/share/lua/5.4/?/init.lua;/root/.luarocks/share/lua/5.4/?.lua;/root/.luarocks/share/lua/5.4/?/init.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;"..package.path;package.cpath="/workspaces/lua-docker/./lua_modules/lib/lua/5.4/?.so;/root/.luarocks/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/?.so;"..package.cpath' $([ "$*" ] || echo -i) "$@"
