#!/bin/sh

LUAROCKS_SYSCONFDIR='/usr/local/etc/luarocks' exec '/usr/local/bin/lua' -e 'package.path="/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/home/lua-user/.luarocks/share/lua/5.4/?.lua;/home/lua-user/.luarocks/share/lua/5.4/?/init.lua";package.cpath="/usr/local/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/loadall.so;./?.so;/home/lua-user/.luarocks/lib/lua/5.4/?.so"' '/usr/local/bin/luarocks' --project-tree /workspaces/lua-docker/lua_modules "$@"
